/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SecondaryInsertionSort */

#ifndef _Included_SecondaryInsertionSort
#define _Included_SecondaryInsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SecondaryInsertionSort
 * Method:    sort
 * Signature: ([IF)V
 */
JNIEXPORT void JNICALL Java_SecondaryInsertionSort_sort
  (JNIEnv *, jobject, jintArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
