/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SecondaryInsertionSort */

#ifndef _Included_SecondaryInsertionSort
#define _Included_SecondaryInsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SecondaryInsertionSort
 * Method:    insertionSort
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDI)V
 */
JNIEXPORT void JNICALL Java_SecondaryInsertionSort_insertionSort
  (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
