/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SecondaryInsertionSort */

#ifndef _Included_SecondaryInsertionSort
#define _Included_SecondaryInsertionSort
#ifdef __cplusplus
extern "C" {
#endif
#undef SecondaryInsertionSort_MIN_PRIORITY
#define SecondaryInsertionSort_MIN_PRIORITY 1L
#undef SecondaryInsertionSort_NORM_PRIORITY
#define SecondaryInsertionSort_NORM_PRIORITY 5L
#undef SecondaryInsertionSort_MAX_PRIORITY
#define SecondaryInsertionSort_MAX_PRIORITY 10L
/*
 * Class:     SecondaryInsertionSort
 * Method:    sort
 * Signature: ([IF)Z
 */
JNIEXPORT jboolean JNICALL Java_SecondaryInsertionSort_sort
  (JNIEnv *, jobject, jintArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
